travello/urls.py
from  django.urls import path
from . import views

app_name='_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('kontak', views.contact, name='kontak'),
    path('tentang', views.about, name='tentang'),
    path('blog', views.blog, name='blog'),
    path('blog-detail/<str:slug>', views.blog_detail, name='blog_detail'),
    path('destinations', views.destinations, name='destinations'),
    path('detail-paket/<str:slug>', views.detail_paket, name='detail_paket')
]

travels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('travello.urls')),
     path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/comps/banners.html
{% load static %}

<div class="home">
    <div class="home_slider_container">
        <div class="owl-carousel owl-theme home_slider">
            
            {% for banner in banners %}
                <div class="owl-item">
                    <div class="background_image" style="background-image:url({{ banner.image.url }});">
                        <div class="overlay"></div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/comps/blogs.html
{% load static %}


<div class="news" id="news">
    <div class="container">
        <div class="row">
            <div class="col-xl-8">
                <div class="news_container">
                    
                    <!-- News Post -->
                     
                     {% if blogs %}
                        
                        {% for item in blogs  %}
                            <div class="news_post d-flex flex-md-row flex-column align-items-start justify-content-start">
                                <div class="news_post_image">
                                    {% if item.image %}
                                     <img src="{{item.image.url}}" alt="">
                                    {% endif %}
                                </div>
                                <div class="news_post_content" style="padding-top: 0;">
                                
                                    <div class="news_post_title"><a href="{% url '_app:blog_detail' item.slug %}">{{item.title}}</a></div>
                                    <div class="news_post_category">
                                        <ul>
                                            <li><a href="#">Penulis: {{item.penulis}}</a></li>
                                        </ul>
                                    </div>
                                    <div class="news_post_text">
                                        <p>{{item.deskripsi}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                            
                     {% else %}
                     <p>Belum ada blog</p>
                     {% endif %}
                        
                  

                </div>
            </div>

          
        </div>
    </div>
</div>

templates/comps/faq.html
{% load static %}
<div class="row">
    <div class="col-md-12">
        <div class="faq mb-4">
            <h2>FAQ</h2>
            <div class="accordion" id="accordionExample">

                <div class="card mb-1">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn text-left" style="white-space: wrap !important; outline: none; box-shadow: none; background-color: transparent; padding: 0;" type="button" data-toggle="collapse"
                                data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                1. Apa syarat dan ketentuan untuk memesan paket wisata?
                            </button>
                        </h2>
                    </div>
            
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            Untuk memesan paket wisata, Anda diharuskan membayar sebesar 20% dari total harga paket sebagai pembayaran awal. Pembayaran sisa harus dilakukan sebelum tanggal keberangkatan. Pastikan untuk membaca syarat dan ketentuan lengkap yang tercantum di situs kami untuk informasi lebih lanjut.
                        </div>
                    </div>
                </div>
                <div class="card mb-1">
                    <div class="card-header" id="headingTwo">
                        <h2 class="mb-0">
                            <button class="btn text-left" type="button" style="white-space: wrap !important; outline: none; box-shadow: none; background-color: transparent; padding: 0;" data-toggle="collapse"
                                data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                2. Metode pembayaran apa saja yang diterima?
                            </button>
                        </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            Kami menerima berbagai metode pembayaran, termasuk transfer bank, kartu kredit, dan pembayaran online. Pilih metode yang paling sesuai untuk Anda saat melakukan pemesanan di situs kami.
                        </div>
                    </div>
                </div>
                <div class="card mb-1">
                    <div class="card-header" id="headingThree">
                        <h2 class="mb-0">
                            <button class="btn text-left" style="white-space: wrap !important; outline: none; box-shadow: none; background-color: transparent; padding: 0;" type="button" data-toggle="collapse"
                                data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                3. Bagaimana kebijakan pembatalan pemesanan?
                            </button>
                        </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body">
                            Kebijakan pembatalan bervariasi tergantung pada paket wisata yang dipesan. Umumnya, pembayaran awal tidak dapat dikembalikan jika Anda membatalkan pemesanan. Silakan cek syarat dan ketentuan pembatalan untuk detail lebih lanjut tentang kebijakan spesifik.
                        </div>
                    </div>
                </div>
                <div class="card mb-1">
                    <div class="card-header" id="headingFour">
                        <h2 class="mb-0">
                            <button class="btn text-left" style="white-space: wrap !important; outline: none; box-shadow: none; background-color: transparent; padding: 0;" type="button" data-toggle="collapse"
                                data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                4. Bagaimana cara mengubah atau memperbarui pemesanan saya?
                            </button>
                        </h2>
                    </div>
                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                        <div class="card-body">
                            Jika Anda perlu mengubah atau memperbarui pemesanan, hubungi layanan pelanggan kami secepatnya. Kami akan membantu Anda dengan perubahan yang diperlukan sesuai dengan ketersediaan dan syarat yang berlaku.
                        </div>
                    </div>
                </div>
               
            </div>
        </div>

    </div>
</div>

templates/comps/footers.html
{% load static %}

<footer class="footer">
    <div class="parallax_background parallax-window" data-parallax="scroll" style="background-color: #135589;" data-speed="0.8"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="newsletter">
                    <div class="newsletter_title_container text-center">
                        <div class="newsletter_title">Berlangganan dengan kami untuk mendapatkan harga yang menarik</div>
                        <div class="newsletter_subtitle">Join sekarang</div>
                    </div>
                    <div class="newsletter_form_container">
                        <form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
                            <div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
                                <div><input type="text" class="newsletter_input newsletter_input_name" id="newsletter_input_name" placeholder="Nama" required="required"><div class="input_border"></div></div>
                                <div><input type="email" class="newsletter_input newsletter_input_email" id="newsletter_input_email" placeholder="e-mail" required="required"><div class="input_border"></div></div>
                            </div>
                            <div><button style="background-color: gray;" class="newsletter_button">subscribe</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row footer_contact_row">
            <div class="col-xl-10 offset-xl-1">
                <div class="row">

                    <!-- Footer Contact Item -->
                    <div class="col-xl-4 footer_contact_col">
                        <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                            <div class="footer_contact_icon"><img src="{% static 'images/sign.svg' %}" alt=""></div>
                            <div class="footer_contact_title">Telepon/wa</div>
                            <div class="footer_contact_list">
                                <ul>
                                    <li>Telepon:  087860371458</li>
                                    <li>Wa: 087860371458</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Footer Contact Item -->
                    <div class="col-xl-4 footer_contact_col">
                        <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                            <div class="footer_contact_icon"><img src="{% static 'images/trekking.svg' %}" alt=""></div>
                            <div class="footer_contact_title">Alamat</div>
                            <div class="footer_contact_list">
                                <ul style="max-width:190px">
                                    <li>Lombok tengah, NTB, Indonesia</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Footer Contact Item -->
                    <div class="col-xl-4 footer_contact_col">
                        <div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
                            <div class="footer_contact_icon"><img src="{% static 'images/around.svg' %}" alt=""></div>
                            <div class="footer_contact_title">Email</div>
                            <div class="footer_contact_list">
                                <ul>
                                    <li>lombokjuragan39@gmail.com</li>
                                    <!-- <li>Office@yourbusinessname.com</li> -->
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div style="background-color: #fff;" class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> 
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>
</footer>

templates/comps/header.html
{% load static %}

templates/comps/intros.html
{% load static %}


<div class="intro">
    <div></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="intro_container">
                    <div class="row">

                        <!-- Intro Item -->
                        <div class="col-lg-4 intro_col">
                            <div class="intro_item d-flex flex-row align-items-end justify-content-start">
                                <div class="intro_icon"><img src="{% static 'images/beach.svg' %}" alt=""></div>
                                <div class="intro_content">
                                    <div class="intro_title">Destinasi Populer</div>
                                    <div class="intro_subtitle"><p>Kami tawarkan destinasi terbaru</p></div>
                                </div>
                            </div>
                        </div>

                        <!-- Intro Item -->
                        <div class="col-lg-4 intro_col">
                            <div class="intro_item d-flex flex-row align-items-end justify-content-start">
                                <div class="intro_icon"><img src="{% static 'images/wallet.svg' %}" alt=""></div>
                                <div class="intro_content">
                                    <div class="intro_title">Harga Bersahabat</div>
                                    <div class="intro_subtitle"><p>Harga yang selalu termurah</p></div>
                                </div>
                            </div>
                        </div>

                        <!-- Intro Item -->
                        <div class="col-lg-4 intro_col">
                            <div class="intro_item d-flex flex-row align-items-end justify-content-start">
                                <div class="intro_icon"><img src="{% static 'images/suitcase.svg' %}" alt=""></div>
                                <div class="intro_content">
                                    <div class="intro_title">Pelayanan Terbaik</div>
                                    <div class="intro_subtitle"><p>Pelayanan lebih kami utamakan</p></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>		
        </div>
    </div>
</div>

templates/comps/menu.html
{% load static %}


<header class="header">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="header_content d-flex flex-row align-items-center justify-content-start">
                    <div class="header_content_inner d-flex flex-row align-items-end justify-content-between">
                        <div class="logo">
                            <a href=".."><img width="250" src="{% static 'images/logo/default.png' %}" alt="logo"></a>
                        </div>
                        <nav class="main_nav">
                            <ul class="d-flex flex-row align-items-center justify-content-start">
                                <li><a href="..">Home</a></li>
                                <li><a href="/tentang">Tentang</a></li>
                                <li><a href="/kontak">Kontak kami</a></li>
                                <li><a href="/blog">Blog</a></li>
                                <a href="tel:087860371458" class="btn btn-primary">Kontak</a>
                            </ul>
                        </nav>



                        <!-- Hamburger -->

                        <div class="hamburger ml-auto">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
   
</header>

<!-- Menu -->

<div class="menu">
    <div class="menu_header d-flex flex-row align-items-center justify-content-start">
        <div class="menu_logo">
            <a href=".."><img width="250" src="{% static 'images/logo/default.png' %}" alt="logo"></a>
        </div>
        <div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
    </div>
    <div class="menu_content">
        <ul>
            <li><a href="..">Home</a></li>
            <li><a href="/tentang">Tentang</a></li>
            <li><a href="/kontak">Kontak kami</a></li>
            <li><a href="/blog">Blog</a></li>
            <a href="tel:087860371458" class="btn btn-primary">Kontak</a>
        </ul>
    </div>
    
</div>

templates/comps/menu_detail.html
{% load static %}


<header class="header">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="header_content d-flex flex-row align-items-center justify-content-start">
                    <div class="header_content_inner d-flex flex-row align-items-end justify-content-between">
                        <div class="logo"><a href=".."><img width="250" src="{% static 'images/logo/default.png' %}" alt="logo"></a></div>
                        <nav class="main_nav">
                            <ul class="d-flex flex-row align-items-center justify-content-start">
                                <li><a href="..">Home</a></li>
                                <li><a href="tentang">Tentang</a></li>
                                <li><a href="kontak">Kontak kami</a></li>
                                <li><a href="blog">Blog</a></li>
                                <a href="tel:087860371458" class="btn btn-primary">Kontak</a>

                               
                            </ul>
                        </nav>



                        <!-- Hamburger -->

                        <div class="hamburger ml-auto">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
   
</header>

<!-- Menu -->

<div class="menu">
    <div class="menu_header d-flex flex-row align-items-center justify-content-start">
        <div class="menu_logo"><a href="..">MandalikaTour</a></div>
        <div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
    </div>
    <div class="menu_content">
        <ul>
            <li><a href="..">Home</a></li>
            <li><a href="tentang">Tentang</a></li>
            <li><a href="blog">Blog</a></li>
            <li><a href="kontak">Kontak</a></li>
        </ul>
    </div>
    
</div>

templates/comps/other_program.html
{% load static %}

<!-- <div class="destinations" id="destinations"> -->
        <div class="row">
            <div class="col text-left">
                <h1 style="margin-bottom: 0px !important;">Paket Lainnya</h1>
                
            </div>
        </div>
        <div class="row destinations_row">
            <div class="col">
                <div class="destinations_container item_grid ">
                    
                    {% if other %}
                    
                    {% for program in other %}
                        <a href="{% url '_app:detail_paket' program.slug %}">
                            <div class="destination item ">
                                <div class="destination_image">
                                    <img src="{{program.image.url}}" alt="">
                                
                                </div>
                                <div class="destination_content px-2">
                                <h3 style="color: #181818; font-size: 16px; font-weight: 600; margin-top: 10px; margin-bottom: 7px !important;">Paket Wisata {{program.name}}</h3>
                                <p style="font-size: 13px; font-weight: 200; color: #72728C;letter-spacing: 0.02em;">Harga Mulai Dari {{program.price}}/ Orang</p>
                                </div>
                            </div>
                        </a>
                        
                    {% endfor %}
                        
                        
                    {% endif %}
                        
                      
                </div>
            </div>
        </div>
<!-- </div> -->

templates/comps/programs.html
{% load static %}

<div class="destinations" id="destinations">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_subtitle">wisata pilihan</div>
                <div class="section_title"><h1>Paket Populer</h1></div>
                <div class="section_desc"><p class="m-auto"  style="max-width: 700px;">
                    Pilihan paket wisata populer yang ada di lombok, dengan varian harga dan destinasi menarik yang bisa anda nikmati bersama kami MANDALIKA tour
                </p></div>
            </div>
        </div>
        <div class="row destinations_row">
            <div class="col">
                <div class="destinations_container item_grid ">
                    
                    {% if programs %}
                        {% for program in programs %}
                        <a href="{% url '_app:detail_paket' program.slug %}">
                            <div class="destination item ">
                                <div class="destination_image">
                                    <img src="{{program.image.url}}" alt="">
                                
                                </div>
                                <div class="destination_content px-2">
                                   <h3 style="color: #181818; font-size: 16px; font-weight: 600; margin-top: 10px; margin-bottom: 7px !important;">Paket Wisata {{program.name}}</h3>
                                   <p style="font-size: 13px; font-weight: 200; color: #72728C;letter-spacing: 0.02em;">Harga Mulai Dari {{program.price}}/ Orang</p>
                                </div>
                            </div>
                        </a>

                        
                        {% endfor %}


                        {% else %}
                        <h1>Kosong</h1>
                    {% endif %}
                        
                </div>
            </div>
        </div>
    </div>
</div>

templates/comps/search.html
{% load static %}

<!-- <div class="home_search">
    <div class="container">
        <div class="row">
            <div class="col-8 col-sm-8 mx-auto text-center">
                <div class="home_search_container">
                    <div class="home_search_content" style="background: transparent !important; bottom:100px !important;">
                        <form action="#" class="home_search_form" id="home_search_form">
                            <div style="position: relative;">
                                <input type="text" class="search_input w-100" placeholder="Kategori" 
                                    required="required" style="padding-left: 40px;">
                                <i class="fas fa-search" 
                                    style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); 
                                    font-size: 18px; color: #aaa;"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->


<div class="home_search">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="home_search_container">
                    <!-- <div class="home_search_title">Cari wisata anda</div> -->
                    <div class="home_search_content">
                        <form action="#" class="home_search_form" id="home_search_form">
                            <div class="d-flex flex-lg-row flex-column align-items-start justify-content-lg-between justify-content-start">
                                <input type="text" class="search_input search_input_1" placeholder="City" required="required">
                                <input type="text" class="search_input search_input_2" placeholder="Departure" required="required">
                                <input type="text" class="search_input search_input_3" placeholder="Arrival" required="required">
                                <input type="text" class="search_input search_input_4" placeholder="Budget" required="required">
                                <button class="home_search_button">search</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/comps/side_blog.html
{% load static %}


<div class="col-lg-4">
    <div class="news_sidebar">

        <!-- Paket wisata -->
        <div class="categories">
            <div class="sidebar_title">Paket Wisata Lombok</div>
            <div class="sidebar_list">
                <ul>
                    {% for item in program  %}
                        <li><a href="{% url '_app:detail_paket' item.slug %}"><div class="d-flex flex-row align-items-start justify-content-start">Paket {{item.name}}<span class="ml-auto">(Rp {{item.price}}/pax)</span></div></a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        
        {% if is_detail_blog %}
            <div class="latest">
                <div class="sidebar_title">Blog Lainnya</div>
                <div class="latest_container">
                    
                    {% for blog in other_blog  %}
                    
                        <!-- Latest blog -->
                        <div class="latest_post d-flex flex-row align-items-start justify-content-start">
                            {% if blog.image %}
                            <div class="latest_post_image"><img src="{{blog.image.url}}" alt=""></div>
                            {% endif %}

                            <div class="latest_post_content">
                                <div class="latest_post_date d-flex flex-row align-items-end justify-content-start" style="margin-top: 0 !important;">
                                    <!-- <div class="latest_post_day">02</div> -->
                                    <div class="latest_post_month">june</div>
                                </div>
                                <div class="latest_post_title"><a href="{% url '_app:blog_detail' blog.slug %}">{{blog.title}}</a></div>
                                    <div class="latest_post_text"><p>{{blog.deskripsi|truncatechars:50 }}</p></div>
                            </div>
                        </div>
                        
                    {% endfor %}
                        
                        
                        

                    
                </div>
            </div>
     
        {% endif %}
            
    

    </div>
</div>

templates/comps/testimonis.html
{% load static %}

<!-- <div class="testimonials" id="testimonials">
    <div class="parallax_background parallax-window" data-parallax="scroll" 
   
    data-speed="0.8"></div>

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_title"><h1>Testimoni Pelanggan</h1></div>
            </div>
        </div>
        <div class="row testimonials_row">
            <div class="col">

                <div class="testimonials_slider_container">
                    <div class="owl-carousel owl-theme testimonials_slider">
                        
                        <div class="owl-item text-center">
                            <div class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. lobortis dolor. Cras placerat lectus a posuere aliquet. Curabitur quis vehicula odio.</div>
                            <div class="testimonial_author">
                                <div class="testimonial_author_content d-flex flex-row align-items-end justify-content-start">
                                    <div>john turner,</div>
                                    <div>client</div>
                                </div>
                            </div>
                        </div>

                        <iframe src='https://widgets.sociablekit.com/google-reviews/iframe/25436681' frameborder='0' width='100%' height='1000'></iframe>

                    

                    </div>
                </div>


            </div>
        </div>
    </div>


    <div class="test_nav">
        <ul class="d-flex flex-column align-items-end justify-content-end">
            <li><a href="#">City Breaks Clients<span>01</span></a></li>
            <li><a href="#">Cruises Clients<span>02</span></a></li>
            <li><a href="#">All Inclusive Clients<span>03</span></a></li>
        </ul>
    </div>
</div> -->



<div class="testimonials" id="testimonials">
    <div class="parallax_background parallax-window" data-parallax="scroll" 
   
    data-speed="0.8"></div>

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_title"><h1>Testimoni Pelanggan</h1></div>
            </div>
        </div>
        <div class="taggbox"  style="width:100%;height:100%" data-widget-id="158601" data-tags="false" ></div><script src="https://widget.taggbox.com/embed-lite.min.js" type="text/javascript"></script>
    </div>


 
</div>